---
- name: Check if installation script exists
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install HTTPS transport for APT
  apt:
    pkg: apt-transport-https
    state: installed
  when: not apt_https_transport.stat.exists

#- name: Import the NodeSource GPG key into apt - keep to revert, current hotfix is a bit dirty
#  apt_key:
#    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#    state: present

- name: Import the NodeSource GPG key into apt
  shell: "curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -"

- name: Add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
    state: present

- name: Add NodeSource deb-src repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
    state: present

- name: Add NodeSource repository preferences
  template:
    src: etc/apt/preferences.d/deb_nodesource_com_node.pref.2
    dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref

- name: Install Node.js
  apt:
    name: nodejs
    state: installed
    update_cache: yes

- name: Install nodejs global packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ nodejs_global_packages }}"