---
env_hostname: ""
env_vars: []
env_timezone: "UTC"
env_cron_jobs: [] # {job: "git status", name: "job name", user: "www-data", minute: "*", hour: "*", day: "*", weekday: "*", month: "*" }
env_hosts: [] # {ip: "127.0.0.1", host: "localhost"}
env_cron_host: false