---
- name: Configure NoGame Vagrant Dev env
  hosts: vagrant
  become: yes
  remote_user: vagrant
  vars:
    tools_absent:
      - apache2

    env_timezone: "UTC"
    env_hostname: "nogame-dev-vagrant"
    env_hosts:
      - {ip: "127.0.0.1", host: "nogame.local"}

    openssl_selfsigned_cert_common_name: "nogame.local"
    openssl_cert_name: "nogame.local"

    pg_version: 9.6
    pg_users: [{name: "nogame", password: "nogame", permissions: "CREATEDB"}]
    pg_databases: [{name: "nogame", owner: "nogame"}]
    pg_postgis: true
    pg_postgis_version: 2.3

  roles:
    - { role: env }
    - { role: tools }
    - { role: php7 }
    - { role: nodejs }
    - { role: openssl }
    - { role: composer }
    - { role: postgresql }
    - { role: disable-apache }
    - { role: nginx }
    - {
        role: nginx_vhost,
        nginx_vhost_host: "client.nogame.local",
        nginx_vhost_web_root: "/var/www/nogame/nodejs/server/client",
        nginx_vhost_web_port: 80
      }
    - {
        role: nginx_vhost,
        nginx_vhost_host: "nogame.local",
        nginx_vhost_web_root: "/var/www/nogame/php/web/public",
        nginx_vhost_web_port: 80
      }